home:
  path: /
  controller: App\Controller\HomeController::hello


Reg_form:
  path: /register
  controller: App\Controller\RegistrationController::reg_form

Reg_submit:
  path: /register/submit
  controller: App\Controller\RegistrationController::reg_submit


log_in_form:
  path: /login
  controller: App\Controller\loginController:log_in_form

log_submit:
  path: /login/submit
  controller: App\Controller\loginController::log_submit

logout:
  path: /logout



show_post:
  path: /blog/{title}
  controller: App\Controller\BlogController::show
  #requirements:
   # num: '\d+'

edit_post:
    path: /blog/delete/{id}
    controller: App\Controller\BlogController::delete
    requirements:
      num: '\d+'

show_all:
  path: /blog
  controller: App\Controller\BlogController::show_all

post_new:
  path: /new
  methods: GET
  controller: App\Controller\BlogController::new

submit_post:
   path: /submit_post
   methods: POST
   controller: App\Controller\BlogController::create







home_auth:
  path : /sign_up/home
  controller : App\Controller\AuthorController::home_auth

sign_up:
  path : /sign_up
  controller : App\Controller\AuthorController::sign_up

all_author:
  path : /authors
  controller : App\Controller\AuthorController::all_authors

a_author:
  path : /authors/{name}
  controller : App\Controller\AuthorController::author

author_post:
  path : /authors/{id}/post
  controller : App\Controller\AuthorController::author_post


about:
  path : /about
  controller: App\Controller\AboutController::about





search:
  path : /search
  controller : App\Controller\SearchController::searchedPost





auth_error:
  path:          /sorry
  controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    # the path of the template to render
    template:  'Error\auth_error.html.twig'


post_error:
  path:          /soorry
  controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    # the path of the template to render
    template:  'Error\post_error.html.twig'


